UsedSale_Car/Models/Classes/CarOwner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UsedSale_Car.Models.Classes
{
    public class CarOwner:Users
    {
       
    }
}

UsedSale_Car/Controllers/CarOwnerController.cs
using UsedSale_Car.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UsedSale_Car.Controllers
{
    public class CarOwnerController : Controller
    {
        Context ca = new Context();
        CarListing cl = new CarListing();


        // GET: CarOwner
        [Authorize]
        public ActionResult CarOwnerIndex()
        {
            string lastName = Session["LastName"] as string;
            string firstName = Session["FirstName"] as string;
            string mail = Session["Mail"] as string;
            string phone = Session["Phone"] as string;
            string password = Session["Password"] as string;
            int id = 0;

            //id si eşleşen araç sahipleri gelsin
            if (Session["ID"] != null && int.TryParse(Session["ID"].ToString(), out int parsedId))
            {
                id = parsedId;
            }



            // View'a kullanıcı bilgilerini taşımak
            ViewBag.LastName = lastName;
            ViewBag.FirstName = firstName;
            ViewBag.Mail = mail;
            ViewBag.Phone = phone;
            ViewBag.Password = password;
            ViewBag.ID = id;

            cl.CarTake = ca.Cars.Where(x => x.CarOwner.ID == id).ToList();
            return View(cl);
        }

        // GET: CarOwner (araba ekleme)
        [HttpGet]
        public ActionResult NewCar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewCar(Car c)
        {

            //Kullanıcı bilgilerini Session'dan almak
            string lastName = Session["LastName"] as string;
            string firstName = Session["FirstName"] as string;
            string mail = Session["Mail"] as string;
            string phone = Session["Phone"] as string;
            string password = Session["Password"] as string;
            int id = 0;

            if (Session["ID"] != null && int.TryParse(Session["ID"].ToString(), out int parsedId))
            {
                id = parsedId;
            }

            ViewBag.LastName = lastName;
            ViewBag.FirstName = firstName;
            ViewBag.Mail = mail;
            ViewBag.Phone = phone;
            ViewBag.Password = password;
            ViewBag.ID = id;
            cl.CarTake = ca.Cars.Where(x => x.CarOwner.ID == id).ToList();
            c.CarOwner.ID = id;
            c.CarOwner.FirstName = firstName;
            c.Approve = false;

            ca.Cars.Add(c);
            ca.SaveChanges();
            return View("CarOwnerIndex");
        }

        // GET: CarOwner (araba silme)
        public ActionResult DeleteCar(int id=0)
        {
            var findedCar = ca.Cars.Find(id);
            ca.Cars.Remove(findedCar);
            ca.SaveChanges();
            return RedirectToAction("CarOwnerIndex");
        }

        // GET: CarOwner (araba güncelleme)
        public ActionResult GetCar(int id=0)
        {
            var findedCar2 = ca.Cars.Find(id);

            return View("GetCar", findedCar2);
        }
        public ActionResult UpdateCar(Car c)
        {
            var findedCar3 = ca.Cars.Find(c.ID);
            findedCar3.Brand.BrandName = c.Brand.BrandName;
            findedCar3.Model.ModelName = c.Model.ModelName;
            findedCar3.CarOwner.Mail = c.CarOwner.Mail;
            findedCar3.PhotoCarURL = c.PhotoCarURL;
            findedCar3.Year = c.Year;
            findedCar3.CarType.Name = c.CarType.Name;
            findedCar3.City.Name = c.City.Name;
            findedCar3.Color.Name = c.Color.Name;
            findedCar3.Description = c.Description;
            findedCar3.Doors = c.Doors;
            findedCar3.Engine = c.Engine;
            findedCar3.Mileage = c.Mileage;
            findedCar3.Price = c.Price;
            findedCar3.FuelType = c.FuelType;
            findedCar3.GearType = c.GearType;
            findedCar3.GlassCeiling = c.GlassCeiling;
            findedCar3.ParkingSensor = c.ParkingSensor;
            findedCar3.CentralLocking = c.CentralLocking;
            findedCar3.FoldableMirror = c.FoldableMirror;
            findedCar3.Approve = c.Approve;
            ca.SaveChanges();
            return RedirectToAction("CarOwnerIndex");
        }
    }
}

UsedSale_Car/Views/CarOwner/CarOwnerIndex.cshtml
@model UsedSale_Car.Models.Classes.CarListing
@{
    ViewBag.Title = "CarOwnerIndex";
    Layout = "~/Views/Shared/_CarOwnerLayout.cshtml";
}

<h5> Araç Sahibi: @ViewBag.FirstName  @ViewBag.LastName </h5>
<h2>ARABALAR</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th> ARABA ID </th>
        <th> ARABA BRAND </th>
        <th> ARABA MODEL </th>
        <th> ARABA FİYAT </th>
        <th> ARABA SİL </th>
        <th> ARABA DÜZENLE </th>
        <th> ARABA DETAYLARI </th>
    </tr>
    @foreach (var x in Model.CarTake)
    {
        <tr>
            <th> @x.ID </th>
            <th> @x.Brand.BrandName </th>
            <th> @x.Model.ModelName </th>
            <th> @x.Price </th>
            <th> <a href="/CarOwner/DeleteCar/@x.ID" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i>Sil</a></th>
            <th> <a href="/CarOwner/GetCar/@x.ID" class="btn btn-warning">Düzenle</a></th>
            <th> <a href="/Car/CarDetail/@x.ID" class="btn btn-primary">Detaylar</a></th>
        </tr>
    }
</table>

<a href="/CarOwner/NewCar/@ViewBag.ID" class="btn btn-info" style="font-size:large">ARABA EKLE</a>

UsedSale_Car/Views/CarOwner/GetCar.cshtml
@model UsedSale_Car.Models.Classes.Car
@{
    ViewBag.Title = "GetCar";
    Layout = "~/Views/Shared/_CarOwnerLayout.cshtml";
}
<h2>Araba Düzenle</h2>
<br />
@using (Html.BeginForm("UpdateCar", "CarOwner", FormMethod.Post))
{
    <p>Araba @Html.LabelFor(x => x.ID)</p>
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control", @readonly = "readonly" })
    <br />
    <p>
        @Html.LabelFor(x => x.CarOwner.FirstName) :  @Html.DisplayFor(x => x.CarOwner.FirstName)
        <br />
        @Html.LabelFor(x => x.CarOwner.LastName)  :  @Html.DisplayFor(x => x.CarOwner.LastName)
        <br />
        @Html.LabelFor(x => x.CarOwner.Phone)  :  @Html.DisplayFor(x => x.CarOwner.Phone)
        <br />
        @Html.LabelFor(x => x.CarOwner.Mail)  :  @Html.DisplayFor(x => x.CarOwner.Mail)
        <br />
    </p>

    <br />
    @Html.LabelFor(x => x.Brand.BrandName)
    @Html.TextBoxFor(x => x.Brand.BrandName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Model.ModelName)
    @Html.TextBoxFor(x => x.Model.ModelName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CarType)
    <p>

        Otomobil @Html.RadioButtonFor(m => m.CarType.Name, "Otomobil")&nbsp;&nbsp;
        Minibüs @Html.RadioButtonFor(m => m.CarType.Name, "Minibüs")&nbsp;&nbsp;
        Otobüs @Html.RadioButtonFor(m => m.CarType.Name, "Otobüs")&nbsp;&nbsp;
        Kamyonet @Html.RadioButtonFor(m => m.CarType.Name, "Kamyonet")&nbsp;&nbsp;
        Kamyon @Html.RadioButtonFor(m => m.CarType.Name, "Kamyon")
    </p>

    <br />
    @Html.LabelFor(x => x.Year)
    @Html.TextBoxFor(x => x.Year, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Mileage)
    @Html.TextBoxFor(x => x.Mileage, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PublicationDate)
    @Html.TextBoxFor(x => x.PublicationDate, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.City)
    <p>

        İzmir @Html.RadioButtonFor(m => m.City.Name, "İzmir") &nbsp;&nbsp;
        Ankara @Html.RadioButtonFor(m => m.City.Name, "Ankara")&nbsp;&nbsp;
        İstanbul @Html.RadioButtonFor(m => m.City.Name, "İstanbul")
    </p>
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    <br />
    @Html.LabelFor(x => x.Color)
    <p>

        Kırmızı @Html.RadioButtonFor(m => m.Color.Name, "Kırmızı")&nbsp;&nbsp;
        Sarı @Html.RadioButtonFor(m => m.Color.Name, "Sarı")&nbsp;&nbsp;
        Yeşil @Html.RadioButtonFor(m => m.Color.Name, "Yeşil")&nbsp;&nbsp;
        Siyah @Html.RadioButtonFor(m => m.Color.Name, "Siyah")&nbsp;&nbsp;
        Beyaz @Html.RadioButtonFor(m => m.Color.Name, "Beyaz")
    </p>
    <br />
    @Html.LabelFor(x => x.Engine)
    @Html.TextBoxFor(x => x.Engine, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FuelType)
    @Html.TextBoxFor(x => x.FuelType, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.GearType)
    @Html.TextBoxFor(x => x.GearType, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Doors)
    @Html.TextBoxFor(x => x.Doors, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FoldableMirror)
    <br />
    @Html.RadioButtonFor(x => x.FoldableMirror, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.FoldableMirror, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.FogLights)
    <br />
    @Html.RadioButtonFor(x => x.FogLights, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.FogLights, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.CentralLocking)
    <br />
    @Html.RadioButtonFor(x => x.CentralLocking, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.CentralLocking, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.GlassCeiling)
    <br />
    @Html.RadioButtonFor(x => x.GlassCeiling, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.GlassCeiling, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.ParkingSensor)
    <br />
    @Html.RadioButtonFor(x => x.ParkingSensor, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.ParkingSensor, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.PhotoCarURL)
    @Html.TextBoxFor(x => x.PhotoCarURL, new { @class = "form-control" })
    <br />


    @Html.LabelFor(x => x.Description)
    @Html.TextAreaFor(x => x.Description, 5, 1, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary" style="font-size:large">Güncelle</button>
    <br />
    <br />

}

UsedSale_Car/Views/CarOwner/NewCar.cshtml
@model UsedSale_Car.Models.Classes.Car

@{
    ViewBag.Title = "NewCar";
    Layout = "~/Views/Shared/_CarOwnerLayout.cshtml";
}

@ViewBag.ID - @ViewBag.FirstName
<h2>Yeni Araba Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.ID)
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control", @readonly = "readonly" })
    <br />
    <p>
        @Html.LabelFor(x => x.CarOwner.FirstName) : @Html.DisplayFor(x => x.CarOwner.FirstName)
        <br />
        @Html.LabelFor(x => x.CarOwner.LastName)  :  @Html.DisplayFor(x => x.CarOwner.LastName)
        <br />
        @Html.LabelFor(x => x.CarOwner.Phone)  :  @Html.DisplayFor(x => x.CarOwner.Phone)
        <br />
        @Html.LabelFor(x => x.CarOwner.Mail)  :  @Html.DisplayFor(x => x.CarOwner.Mail)
    </p>
    <br />
    @Html.LabelFor(x => x.Brand.BrandName)
    @Html.TextBoxFor(x => x.Brand.BrandName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Model.ModelName)
    @Html.TextBoxFor(x => x.Model.ModelName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CarType)
    <p>

        Otomobil @Html.RadioButtonFor(m => m.CarType.Name, "Otomobil")&nbsp;&nbsp;
        Minibüs @Html.RadioButtonFor(m => m.CarType.Name, "Minibüs")&nbsp;&nbsp;
        Otobüs @Html.RadioButtonFor(m => m.CarType.Name, "Otobüs")&nbsp;&nbsp;
        Kamyonet @Html.RadioButtonFor(m => m.CarType.Name, "Kamyonet")&nbsp;&nbsp;
        Kamyon @Html.RadioButtonFor(m => m.CarType.Name, "Kamyon")
    </p>

    <br />
    @Html.LabelFor(x => x.Year)
    @Html.TextBoxFor(x => x.Year, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.City)
    <p>

        İzmir @Html.RadioButtonFor(m => m.City.Name, "İzmir") &nbsp;&nbsp;
        Ankara @Html.RadioButtonFor(m => m.City.Name, "Ankara")&nbsp;&nbsp;
        İstanbul @Html.RadioButtonFor(m => m.City.Name, "İstanbul")
    </p>
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Mileage)
    @Html.TextBoxFor(x => x.Mileage, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PublicationDate)
    @Html.TextBoxFor(x => x.PublicationDate, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Color)
    <p>

        Kırmızı @Html.RadioButtonFor(m => m.Color.Name, "Kırmızı")&nbsp;&nbsp;
        Sarı @Html.RadioButtonFor(m => m.Color.Name, "Sarı")&nbsp;&nbsp;
        Yeşil @Html.RadioButtonFor(m => m.Color.Name, "Yeşil")&nbsp;&nbsp;
        Siyah @Html.RadioButtonFor(m => m.Color.Name, "Siyah")&nbsp;&nbsp;
        Beyaz @Html.RadioButtonFor(m => m.Color.Name, "Beyaz")
    </p>
    <br />
    @Html.LabelFor(x => x.Engine)
    @Html.TextBoxFor(x => x.Engine, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FuelType)
    @Html.TextBoxFor(x => x.FuelType, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.GearType)
    @Html.TextBoxFor(x => x.GearType, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Doors)
    @Html.TextBoxFor(x => x.Doors, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FoldableMirror)
    <br />
    @Html.RadioButtonFor(x => x.FoldableMirror, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.FoldableMirror, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.FogLights)
    <br />
    @Html.RadioButtonFor(x => x.FogLights, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.FogLights, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.CentralLocking)
    <br />
    @Html.RadioButtonFor(x => x.CentralLocking, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.CentralLocking, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.GlassCeiling)
    <br />
    @Html.RadioButtonFor(x => x.GlassCeiling, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.GlassCeiling, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.ParkingSensor)
    <br />
    @Html.RadioButtonFor(x => x.ParkingSensor, true, new { @class = "form-check-input" })
    <label class="form-check-label">Var</label>
    <br />
    @Html.RadioButtonFor(x => x.ParkingSensor, false, new { @class = "form-check-input" })
    <label class="form-check-label">Yok</label>
    <br />
    <br />
    @Html.LabelFor(x => x.PhotoCarURL)
    @Html.TextBoxFor(x => x.PhotoCarURL, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Description)
    @Html.TextAreaFor(x => x.Description, 5, 1, new { @class = "form-control" })
    <br />



    <button class="btn btn-primary" style="font-size:large">Araba Ekle</button>
    <br />
    <br />
</form>